<?php

/**
 * AccountsApiTest
 * PHP version 8.1
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 */

/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.2.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

namespace Accounting\Test\Api;

use Accounting\ApiException;
use PHPUnit\Framework\TestCase;
use Accounting\Accounting;
use GuzzleHttp\HandlerStack;
use Accounting\Test\TestHandler;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use Accounting\Api\AccountsApi;

/**
 * AccountsApiTest Class Doc Comment
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 *
 * @covers AccountsApi
 * @uses Accounting
 */
class AccountsApiTest extends TestCase
{
    /**
     * Test case for addAccount
     *
     * Add an account.
     *
     */
    public function testAddAccount()
    {
        $path = "/accounts";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("POST", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->accounts()->addAccount(["test" => true], ));
    }

    /**
     * Test case for deleteAccount
     *
     * Delete an account.
     *
     */
    public function testDeleteAccount()
    {
        $path = "/accounts/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("DELETE", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->accounts()->deleteAccount('uuid_example', ));
    }

    /**
     * Test case for getAccount
     *
     * Get an account.
     *
     */
    public function testGetAccount()
    {
        $path = "/accounts/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->accounts()->getAccount('uuid_example', ));
    }

    /**
     * Test case for listAccounts
     *
     * List company's accounts.
     *
     */
    public function testListAccounts()
    {
        $path = "/accounts";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->accounts()->listAccounts('fields_example', 'page_example', 'perPage_example', ));
    }

    /**
     * Test case for updateAccount
     *
     * Update an account.
     *
     */
    public function testUpdateAccount()
    {
        $path = "/accounts/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("PUT", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->accounts()->updateAccount('uuid_example', ["test" => true], ));
    }
}
