<?php

/**
 * CategoriesApiTest
 * PHP version 8.1
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 */

/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.9
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

namespace Accounting\Test\Api;

use Accounting\ApiException;
use PHPUnit\Framework\TestCase;
use Accounting\Accounting;
use GuzzleHttp\HandlerStack;
use Accounting\Test\TestHandler;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use Accounting\Api\CategoriesApi;

/**
 * CategoriesApiTest Class Doc Comment
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 *
 * @covers CategoriesApi
 * @uses Accounting
 */
class CategoriesApiTest extends TestCase
{
    /**
     * Test case for addCategory
     *
     * Add a category.
     *
     */
    public function testAddCategory()
    {
        $path = "/categories";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("POST", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->categories()->addCategory(["test" => true], ));
    }

    /**
     * Test case for deleteCategory
     *
     * Delete a category.
     *
     */
    public function testDeleteCategory()
    {
        $path = "/categories/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("DELETE", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->categories()->deleteCategory('uuid_example', ));
    }

    /**
     * Test case for getCategory
     *
     * Get a category.
     *
     */
    public function testGetCategory()
    {
        $path = "/categories/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->categories()->getCategory('uuid_example', ));
    }

    /**
     * Test case for listCategories
     *
     * List company's categories.
     *
     */
    public function testListCategories()
    {
        $path = "/categories";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->categories()->listCategories('fields_example', 'page_example', 'perPage_example', ));
    }

    /**
     * Test case for updateCategory
     *
     * Update a category.
     *
     */
    public function testUpdateCategory()
    {
        $path = "/categories/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("PUT", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->categories()->updateCategory('uuid_example', ["test" => true], ));
    }
}
