<?php

/**
 * ContactsApiTest
 * PHP version 8.1
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 */

/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.16
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

namespace Accounting\Test\Api;

use Accounting\ApiException;
use PHPUnit\Framework\TestCase;
use Accounting\Accounting;
use GuzzleHttp\HandlerStack;
use Accounting\Test\TestHandler;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use Accounting\Api\ContactsApi;

/**
 * ContactsApiTest Class Doc Comment
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 *
 * @covers ContactsApi
 * @uses Accounting
 */
class ContactsApiTest extends TestCase
{
    /**
     * Test case for addContact
     *
     * Create a new contact.
     *
     */
    public function testAddContact()
    {
        $path = "/contacts";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("POST", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->contacts()->addContact(["test" => true], ));
    }

    /**
     * Test case for deleteContact
     *
     * Delete a contact.
     *
     */
    public function testDeleteContact()
    {
        $path = "/contacts/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("DELETE", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->contacts()->deleteContact('uuid_example', ));
    }

    /**
     * Test case for getContact
     *
     * Retrieve a contact.
     *
     */
    public function testGetContact()
    {
        $path = "/contacts/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->contacts()->getContact('uuid_example', ));
    }

    /**
     * Test case for listContactBills
     *
     * List a contact's bills.
     *
     */
    public function testListContactBills()
    {
        $path = "/contacts/{uuid}/bills";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->contacts()->listContactBills('uuid_example', 'fields_example', 'page_example', 'perPage_example', ));
    }

    /**
     * Test case for listContactInvoices
     *
     * List a contact's invoices.
     *
     */
    public function testListContactInvoices()
    {
        $path = "/contacts/{uuid}/invoices";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->contacts()->listContactInvoices('uuid_example', 'fields_example', 'page_example', 'perPage_example', ));
    }

    /**
     * Test case for listContacts
     *
     * List company's contacts.
     *
     */
    public function testListContacts()
    {
        $path = "/contacts";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->contacts()->listContacts('fields_example', 'page_example', 'perPage_example', ));
    }

    /**
     * Test case for updateContact
     *
     * Update a contact.
     *
     */
    public function testUpdateContact()
    {
        $path = "/contacts/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("PUT", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->contacts()->updateContact('uuid_example', ["test" => true], ));
    }
}
