<?php

/**
 * StatisticsApiTest
 * PHP version 8.1
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 */

/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.9
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

namespace Accounting\Test\Api;

use Accounting\ApiException;
use PHPUnit\Framework\TestCase;
use Accounting\Accounting;
use GuzzleHttp\HandlerStack;
use Accounting\Test\TestHandler;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use Accounting\Api\StatisticsApi;

/**
 * StatisticsApiTest Class Doc Comment
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 *
 * @covers StatisticsApi
 * @uses Accounting
 */
class StatisticsApiTest extends TestCase
{
    /**
     * Test case for summaryStatisticsPeriod
     *
     * Company's summary statistics.
     *
     */
    public function testSummaryStatisticsPeriod()
    {
        $path = "/companies/{uuid}/statistics/summary";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->statistics()->summaryStatisticsPeriod('uuid_example', new \DateTime("2013-10-20T19:20:30+01:00"), new \DateTime("2013-10-20T19:20:30+01:00"), ));
    }
}
