<?php
/**
 * TagsApiTest
 * PHP version 8.1
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 */

/**
 * Accounting API
 *
 * The version of the OpenAPI document: 7.5.5
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

namespace Accounting\Test\Api;

use Accounting\ApiException;
use PHPUnit\Framework\TestCase;
use Accounting\Accounting;
use GuzzleHttp\HandlerStack;
use Accounting\Test\TestHandler;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use Accounting\Api\TagsApi;

/**
 * TagsApiTest Class Doc Comment
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 *
 * @covers TagsApi
 * @uses Accounting
 */
class TagsApiTest extends TestCase
{
    /**
     * Test case for addTag
     *
     * Add a tag.
     *
     */
    public function testAddTag()
    {
        $path = "/tags";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("POST", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->tags()->addTag(["test" => true], ));
    }

    /**
     * Test case for deleteTag
     *
     * Delete a tag.
     *
     */
    public function testDeleteTag()
    {
        $path = "/tags/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("DELETE", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->tags()->deleteTag('uuid_example', ));
    }

    /**
     * Test case for getTag
     *
     * Get a tag.
     *
     */
    public function testGetTag()
    {
        $path = "/tags/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->tags()->getTag('uuid_example', ));
    }

    /**
     * Test case for listTags
     *
     * List company's tags.
     *
     */
    public function testListTags()
    {
        $path = "/tags";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->tags()->listTags('fields_example', 'page_example', 'perPage_example', ));
    }

    /**
     * Test case for listTagsByResource
     *
     * List company's tags by resource attachment.
     *
     */
    public function testListTagsByResource()
    {
        $path = "/tags/attachments/{resource}";
        $path = str_replace('{' . 'resource' . '}', 'resource_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->tags()->listTagsByResource('resource_example', 'fields_example', 'page_example', 'perPage_example', ));
    }

    /**
     * Test case for updateTag
     *
     * Update a tag.
     *
     */
    public function testUpdateTag()
    {
        $path = "/tags/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("PUT", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->tags()->updateTag('uuid_example', ["test" => true], ));
    }
}
