<?php

/**
 * WebhooksApiTest
 * PHP version 8.1
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 */

/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.12
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

namespace Accounting\Test\Api;

use Accounting\ApiException;
use PHPUnit\Framework\TestCase;
use Accounting\Accounting;
use GuzzleHttp\HandlerStack;
use Accounting\Test\TestHandler;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use Accounting\Api\WebhooksApi;

/**
 * WebhooksApiTest Class Doc Comment
 *
 * @package  Accounting
 * @author   STAN-TAB CORP. LTD
 * @link     https://accounting.sh
 *
 * @covers WebhooksApi
 * @uses Accounting
 */
class WebhooksApiTest extends TestCase
{
    /**
     * Test case for addWebhook
     *
     * Add a webhook.
     *
     */
    public function testAddWebhook()
    {
        $path = "/webhooks";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("POST", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->webhooks()->addWebhook(["test" => true], ));
    }

    /**
     * Test case for deleteWebhook
     *
     * Delete a webhook.
     *
     */
    public function testDeleteWebhook()
    {
        $path = "/webhooks/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("DELETE", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->webhooks()->deleteWebhook('uuid_example', ));
    }

    /**
     * Test case for getWebhook
     *
     * Get a webhook.
     *
     */
    public function testGetWebhook()
    {
        $path = "/webhooks/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->webhooks()->getWebhook('uuid_example', ));
    }

    /**
     * Test case for getWebhookHistory
     *
     * Get webhook's history.
     *
     */
    public function testGetWebhookHistory()
    {
        $path = "/webhooks/{uuid}/history";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->webhooks()->getWebhookHistory('uuid_example', ));
    }

    /**
     * Test case for listWebhookEvents
     *
     * List available webhook events.
     *
     */
    public function testListWebhookEvents()
    {
        $path = "/webhooks/events";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->webhooks()->listWebhookEvents());
    }

    /**
     * Test case for listWebhooks
     *
     * List company's webhooks.
     *
     */
    public function testListWebhooks()
    {
        $path = "/webhooks";

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("GET", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->webhooks()->listWebhooks('fields_example', 'page_example', 'perPage_example', ));
    }

    /**
     * Test case for updateWebhook
     *
     * Update a webhook.
     *
     */
    public function testUpdateWebhook()
    {
        $path = "/webhooks/{uuid}";
        $path = str_replace('{' . 'uuid' . '}', 'uuid_example', $path);

        $api = new Accounting("fake-token", options: [
            'handler' => HandlerStack::create(new TestHandler("PUT", $path, null, "fake-token"))
        ]);
        $this->assertNotNull($api->webhooks()->updateWebhook(["test" => true], 'uuid_example', ));
    }
}
